schemaVersion: 1.1.0
locale: "en"
groupings:
  - title: "OCI KMS"
    variables:
    - compartment_ocid
    - display_name


variables:
  compartment_id:
    type: oci:identity:compartment:id
    title: Target Compartment
    description: The target compartment id where to deploy KMS (Vault and Key).
    required: true

  display_name:
    type: string
    title: KMS Display Name
    description: Vault and Key display name's get derived from this value.
    required: true